CC = gcc
AR = ar
CFLAGS = -O2 -Wall -g
LFLAGS = -lm

# Change this if installed elsewhere
LIBBCM2835 = /usr/local/lib/libbcm2835.a

# Comment these out if you don't want LHA decompression
USE_LIBLHASA=-DUSE_LIBLHASA
LIBLHASA_INCLUDEDIR = -I/usr/include/liblhasa-1.0
LIBLHASA_LIB = -llhasa
