all:

clean:
	rm -f *~ ea.ym ea.ym5 \
		ar_it.ym ar_it.ym5 \
		dascon_mb.ym dascon_mb.ym5 \
		mmcm_sr.ym mmcm_sr.ym5 \
		mmcm_os.ym mmcm_os.ym5 \
		dya_dotd_pt1.ym dya_dotd_pt1.ym5 \
		dya_dotd_pt2.ym dya_dotd_pt2.ym5 \
		cr.ym cr.ym5 \
		ri.ym ri.ym5 \
		vc_ifr.ym vc_ifr.ym5


