all:	
	cd lib && make
	cd blink_leds && make
	cd lcd_display && make
	cd push_button && make
	cd pwm && make

clean:
	cd lib && make clean
	cd blink_leds && make clean
	cd lcd_display && make clean
	cd push_button && make clean
	cd pwm && make clean
