all:	
	cd lib && make
	cd blink_leds && make
	cd lcd_display && make
	cd push_button && make
	cd pwm && make

clean:
	cd lib && make clean
	cd asm_blink_leds && make clean
	cd asm_int_delay && make clean
	cd asm_pwm_dimming && make clean
	cd asm_pwm_leds && make clean
	cd asm_range_finder && make clean
	cd blink_leds && make clean
	cd lcd_display && make clean
	cd push_button && make clean
	cd pwm && make clean
	cd range_finder && make clean
	rm *~

